apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  sources:
  - chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.14.3
    helm:
      releaseName: crossplane
  - repoURL: https://github.com/hegerdes/GitOps.git
    targetRevision: HEAD
    path: infra/hcloud-test/crossplane
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane-system
  info:
    - name: 'Chart Info'
      value: 'https://artifacthub.io/packages/helm/crossplane/crossplane'
  syncPolicy:
    # preserveResourcesOnDeletion: true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
