apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.13.3
    helm:
      releaseName: sealed-secrets
      valuesObject:
        secretName: kubeseal-key
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sealed-secrets
  info:
    - name: 'Chart Info'
      value: 'https://artifacthub.io/packages/helm/bitnami-labs/sealed-secrets'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
