#cloud-config

ssh_pwauth: false
disable_root_opts: no-port-forwarding,no-agent-forwarding,no-X11-forwarding

# Install base packages
package_update: true
package_upgrade: true
packages:
  - gnupg
  - lsb-release
  - ca-certificates
  - pigz # fast decompress for container image
  - isal # even faster decompress for container image
  - cryptsetup # support LUKS disk encryptio
  - apparmor
  - apparmor-profiles-extra
  - apt-transport-https
  - python3-debian
  - jq # json parsing and validating
  - yq # yaml parsing and validating
  - unzip
  - socat
  - mtr-tiny
  - logrotate
  - open-iscsi
  - fuse
  - ipvsadm
  - auditd
  - dbus
  - libyajl2 # Needed for youki wasm
  # - policycoreutils
  # - selinux-basics
  # - selinux-policy-default
  # - semodule-utils
  # - setools

apt_get_command:
  [
    "apt-get",
    "--option=Dpkg::Options::=--force-confold",
    "--option=Dpkg::options::=--force-unsafe-io",
    "--assume-yes",
    "--quiet",
    "--no-install-recommends",
  ]

write_files:
  - path: /etc/dpkg/dpkg.cfg.d/01_nodoc
    content: |
      path-exclude /usr/share/doc/*
      # Need to keep copyright files for legal reasons
      # path-include /usr/share/doc/*/copyright
      path-exclude /usr/share/man/*
      path-exclude /usr/share/groff/*
      path-exclude /usr/share/info/*
      path-exclude /usr/share/lintian/*
      path-exclude /usr/share/linda/*
