#cloud-config

ssh_pwauth: false
disable_root_opts: no-port-forwarding,no-agent-forwarding,no-X11-forwarding

# Install base packages
package_update: true
package_upgrade: true
packages:
  - gnupg
  - lsb-release
  - ca-certificates
  - curl
  - pigz # fast decompress for container image
  - isal # even faster decompress for container image
  - cryptsetup # support LUKS disk encryptio
  - apparmor
  - apparmor-profiles-extra
  - apt-transport-https
  - python3-kubernetes # for ansibl
  - jq # json parsing and validatin
  - yq # yaml parsing and validatin
  - criu # low level cri cli - not needed for k8s >=1.3
  - unzip
  - socat
  - mtr-tiny
  - logrotate
  - open-iscsi
  - ipvsadm
  - auditd
  - dbus
  - libyajl2 # Needed for youki was
  # - policycoreutils
  # - selinux-basics
  # - selinux-policy-default
  # - semodule-utils
  # - setools

apt_get_command:
  [
    "apt-get",
    "--option=Dpkg::Options::=--force-confold",
    "--option=Dpkg::options::=--force-unsafe-io",
    "--assume-yes",
    "--quiet",
    "--no-install-recommends",
  ]
