apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-external-dns-123-preview
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: external-dns-aws
    creationPolicy: Owner

  data:
    - secretKey: credentials
      remoteRef:
        key: k8s-external-dns-creds-aws-123-preview
        decodingStrategy: Auto # can be None, Base64, Base64URL or Auto
