apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-agent-token
  namespace: gitlab-agent
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: gitlab-agent-token
    creationPolicy: Owner

  data:
    - secretKey: token
      remoteRef:
        key: k8s-gitlab-agent-token-gitops
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
