apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aad-sp-external-dns-cloudflare
  namespace: external-dns
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store # name of the SecretStore (or kind specified)
  target:
    name: external-dns-cloudflare # name of the k8s Secret to be created
    creationPolicy: Owner
  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: apiToken
      remoteRef:
        key: cloudflare-dns-henrikgerdes-me
        decodingStrategy: Auto # can be None, Base64, Base64URL or Auto
