apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aad-sp-external-dns-cloudflare
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: external-dns-cloudflare
    creationPolicy: Owner

  data:
    - secretKey: apiToken
      remoteRef:
        key: cloudflare-dns-henrikgerdes-me
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
