apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-agent-token
  namespace: gitlab-agent
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store               # name of the SecretStore (or kind specified)
  target:
    name: gitlab-agent-token  # name of the k8s Secret to be created
    creationPolicy: Owner
  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: gitlab-agent-token
      remoteRef:
        key: k8s-gitlab-agent-token-gitops
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
