grafana:
  replicas: 3
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
    pathType: Prefix
    path: /
    hosts:
      - grafana.k8s.henrikgerdes.me
    tls:
      - secretName: ing-ssl-grafana
        hosts:
        - grafana.k8s.henrikgerdes.me

  # Administrator credentials when not using an existing secret (see below)
  adminUser: admin
  adminPassword: MySuperSecurePassword4U
