apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-agent-loki-cred
  namespace: monitoring
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store               # name of the SecretStore (or kind specified)
  target:
    name: grafana-agent-loki-cred  # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          mylable: external
        annotations:
          myannotation: external
      data:
        host: https://logs-prod-eu-west-0.grafana.net
        username: '{{ .username }}'
        password: '{{ .password }}'
  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        key: grafana-cloud-loki-user
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        key: grafana-cloud-loki-token
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
        metadataPolicy: None
