apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-hegerdes
spec:
  ca:
    secretName: ca-hegerdes
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ca-hegerdes
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: ca-hegerdes
    creationPolicy: Owner

  data:
    - secretKey: tls.crt
      remoteRef:
        key: tls-hegerdes-local-crt
        decodingStrategy: Auto # can be None, Base64, Base64URL or Auto
    - secretKey: tls.key
      remoteRef:
        key: tls-hegerdes-local-key
        decodingStrategy: Auto # can be None, Base64, Base64URL or Auto
