apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - chart: hcloud-cloud-controller-manager
      repoURL: https://charts.hetzner.cloud
      targetRevision: 1.*
      helm:
        releaseName: hcloud-cloud-controller-manager
        valuesObject:
          args:
            cloud-provider: hcloud
            profiling: "false"
          rbac:
            create: false
          networking:
            enabled: true
            clusterCIDR: 10.244.0.0/16
          env:
            HCLOUD_TOKEN: null
            HCLOUD_INSTANCES_ADDRESS_FAMILY:
              value: dualstack # ipv4 (default), ipv6 or dualstack
            HCLOUD_TOKEN_FILE:
              value: /var/run/secrets/hcloud/token
          #   HCLOUD_DEBUG:
          #     value: "true"
          # args:
          #   cloud-provider: hcloud
          #   allow-untagged-cloud: ""
          #   v: 9
          extraVolumeMounts:
            - name: hcloud-token
              mountPath: /var/run/secrets/hcloud
              readOnly: true
          extraVolumes:
            - name: hcloud-token
              secret:
                secretName: hcloud
    - chart: hcloud-csi
      repoURL: https://charts.hetzner.cloud
      targetRevision: 2.*
      helm:
        releaseName: hcloud-csi
        valuesObject:
          metrics:
            enabled: true
          controller:
            hcloudToken:
              file: /var/run/secrets/hcloud/token
            extraVolumeMounts:
              - name: hcloud-token
                mountPath: /var/run/secrets/hcloud
                readOnly: true
            extraVolumes:
              - name: hcloud-token
                secret:
                  secretName: hcloud
    - chart: hcloud-exporter
      repoURL: https://promhippie.github.io/charts
      targetRevision: 3.*
      helm:
        releaseName: hcloud-exporter
        valuesObject:
          collector:
            floatingIps: false
            pricing: false
            images: true
            servers: true
            serverMetrics: true
            loadBalancers: true
            sshKeys: true
            volumes: true
          config:
            token: file:///var/run/secrets/hcloud/token
            # tokenKey: token
            # existingSecret: hcloud
          serviceMonitor:
            enabled: true
          extraEnvVariables:
            HCLOUD_EXPORTER_LOG_PRETTY: "true"
          extraVolumeMounts:
            - name: hcloud-token
              mountPath: /var/run/secrets/hcloud
              readOnly: true
          extraVolumes:
            - name: hcloud-token
              secret:
                secretName: hcloud
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
    # - chart: hetzner-load-balancer-exporter
    #   repoURL: https://wacken89.github.io/hetzner-load-balancer-prometheus-exporter
    #   targetRevision: 1.*
    #   helm:
    #     releaseName: hcloud-lb-exporter
    #     valuesObject:
    #       env:
    #         - name: LOAD_BALANCER_IDS
    #           value: "all"
    #         - name: SCRAPE_INTERVAL
    #           value: "30"
    #         - name: ACCESS_TOKEN
    #           valueFrom:
    #             secretKeyRef:
    #               key: token
    #               name: hcloud
    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-cluster-hcloud-critical/hcloud
      directory:
        jsonnet: {}
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  info:
    - name: Chart-Info Hetzner-Cloud-Controller
      value: https://github.com/hetznercloud/hcloud-cloud-controller-manager
    - name: Chart-Info Hetzner-CSI-Driver
      value: https://github.com/hetznercloud/csi-driver
    - name: Chart-Info Hetzner-Exporter
      value: https://github.com/promhippie/charts/tree/master/stable/hcloud-exporter
    # - name: Chart-Info Hetzner-LB-Exporter
    #   value: https://github.com/wacken89/hetzner-load-balancer-prometheus-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
