apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-store-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - chart: secrets-store-csi-driver
      repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      targetRevision: 1.*
      helm:
        releaseName: secret-store-csi
        valuesObject:
          linux:
            podAnnotations:
              cluster-autoscaler.kubernetes.io/enable-ds-eviction: "true"
    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-cluster-hcloud-critical/secret-store-csi
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/secret-store-csi-driver/secrets-store-csi-driver
    - name: App-Source
      value: https://github.com/kubernetes-sigs/secrets-store-csi-driver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
