apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    - chart: k8s-monitoring
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 2.*
      helm:
        releaseName: grafana-monitoring
        valueFiles:
          - $values/k8s-cluster-hcloud-critical/grafana-monitoring/helm-values-argocd.yml
    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-cluster-hcloud-critical/grafana-monitoring
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/grafana/k8s-monitoring
    - name: App-Source
      value: https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
