apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    - chart: k8s-monitoring
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.*
      helm:
        releaseName: grafana-monitoring
        valuesObject:
          cluster:
            name: hetzner-k8s
          externalServices:
            prometheus:
              hostKey: host
              # host: https://prometheus-prod-01-eu-west-0.grafana.net
              # Authenticate to Prometheus using basic authentication
              basicAuth:
                usernameKey: username
                passwordKey: password
              # Credential management
              secret:
                create: false
                name: grafana-agent-prometheus-cred
                namespace: monitoring
            loki:
              hostKey: host
              # host: https://logs-prod-eu-west-0.grafana.net
              # Authenticate to Prometheus using basic authentication
              basicAuth:
                usernameKey: username
                passwordKey: password
              # Credential management
              secret:
                create: false
                name: grafana-agent-loki-cred
                namespace: monitoring
            tempo:
              # protocol: otlphttp # "otlp" or "otlphttp"
              # host: https://tempo-eu-west-0.grafana.net
              basicAuth:
                usernameKey: username
                passwordKey: password
              secret:
                create: false
                name: grafana-agent-tempo-cred
                namespace: monitoring
          opencost:
            enabled: true
            opencost:
              exporter:
                defaultClusterId: hetzner-k8s
              prometheus:
                existingSecretName: grafana-agent-prometheus-cred
                username_key: username
                password_key: password
                external:
                  url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom
          metrics:
            enabled: true
            cost:
              enabled: true
            node-exporter:
              enabled: true
          traces:
            enabled: true
          logs:
            enabled: true
            pod_logs:
              enabled: true
            cluster_events:
              enabled: true
          receivers:
            grpc:
              enabled: true
            http:
              enabled: true
            zipkin:
              enabled: true
          kube-state-metrics:
            enabled: true
          prometheus-node-exporter:
            enabled: true
          prometheus-operator-crds:
            enabled: true
          alloy: {}
          alloy-events: {}
          alloy-logs: {}
    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-cluster-hcloud-critical/grafana-alloy
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/grafana/k8s-monitoring
    - name: App-Source
      value: https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
