apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    chart: openebs
    repoURL: https://openebs.github.io/openebs
    targetRevision: 4.*
    helm:
      releaseName: openebs
      valuesObject:
        engines:
          local:
            lvm:
              enabled: true
            zfs:
              enabled: false
          replicated:
            mayastor:
              enabled: false
        loki:
          enabled: false
          localpvScConfig:
            enabled: false
          minio:
            enabled: false
        alloy:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/openebs/openebs
    - name: App-Source
      value: https://github.com/openebs/openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
