apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.*
      helm:
        releaseName: cert-manager
        valuesObject:
          crds:
            enabled: true
          extraArgs:
            - --enable-gateway-api
          prometheus:
            serviceMonitor:
              enabled: true
          # podDnsPolicy: None
          # podDnsConfig:
          #   nameservers:
          #     - "1.1.1.1"
          #     - "8.8.8.8"
    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-cluster-hcloud-critical/cert-manager
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - name: App-Source
      value: https://github.com/cert-manager/cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
