apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-azure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - chart: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns/
      targetRevision: 1.*
      helm:
        releaseName: external-dns-azure
        valuesObject:
          provider: azure
          extraArgs: [--exclude-target-net=10.0.0.0/8]
          domainFilters:
            - demeter-discovery.com
          sources:
            - service
            - ingress
            - gateway-httproute
            # - gateway-tlsroute
            # - gateway-tcproute
            # - gateway-udproute
          rbac:
            create: true
            additionalPermissions:
              - apiGroups: ["gateway.networking.k8s.io"]
                resources:
                  [
                    "gateways",
                    "httproutes",
                    "tlsroutes",
                    "tcproutes",
                    "udproutes",
                  ]
                verbs: ["get", "watch", "list"]
          extraVolumes:
            - name: secrets
              secret:
                secretName: external-dns-azure
                items:
                  - key: azure.json
                    path: azure.json
          extraVolumeMounts:
            - name: secrets
              mountPath: /etc/kubernetes/azure.json
              subPath: azure.json
    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-cluster-hcloud-critical/external-dns/azure
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/external-dns/external-dns
    - name: App-Source
      value: https://github.com/kubernetes-sigs/external-dns/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
