# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/k8s-monitoring-helm/refs/heads/main/charts/k8s-monitoring/values.schema.json

# Examples https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/docs/examples/features/cluster-events/default/values.yaml

cluster:
  name: hetzner-k8s

global:
  scrapeInterval: 30s

destinations:
  - name: grafana-com-metrics
    type: prometheus
    url: https://prometheus-prod-01-eu-west-0.grafana.net/api/v1/write
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: grafana-agent-prometheus-cred
      namespace: monitoring

  - name: grafana-com-loki
    type: loki
    url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: grafana-agent-loki-cred
      namespace: monitoring

  - name: grafana-com-tempo
    type: otlp
    url: https://tempo-eu-west-0.grafana.net:443
    metrics: { enabled: true }
    logs: { enabled: true }
    traces: { enabled: true }
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: grafana-agent-tempo-cred
      namespace: monitoring

clusterMetrics:
  enabled: true

clusterEvents:
  enabled: true

nodeLogs:
  enabled: true

podLogs:
  enabled: true

alloy-metrics:
  enabled: true

alloy-logs:
  enabled: true

alloy-receiver:
  enabled: true

alloy-singleton:
  enabled: true

prometheusOperatorObjects:
  enabled: true

applicationObservability:
  enabled: true
  receivers:
    jaeger:
      grpc:
        enabled: true
extraObjects: []

---
externalServices:
  prometheus:
    hostKey: host
    # host: https://prometheus-prod-01-eu-west-0.grafana.net
    # Authenticate to Prometheus using basic authentication
    basicAuth:
      usernameKey: username
      passwordKey: password
    # Credential management
    secret:
      create: false
      name: grafana-agent-prometheus-cred
      namespace: monitoring
  loki:
    hostKey: host
    # host: https://logs-prod-eu-west-0.grafana.net
    # Authenticate to Prometheus using basic authentication
    basicAuth:
      usernameKey: username
      passwordKey: password
    # Credential management
    secret:
      create: false
      name: grafana-agent-loki-cred
      namespace: monitoring
  tempo:
    # protocol: otlphttp # "otlp" or "otlphttp"
    # host: https://tempo-eu-west-0.grafana.net
    basicAuth:
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: grafana-agent-tempo-cred
      namespace: monitoring
opencost:
  enabled: true
  opencost:
    exporter:
      defaultClusterId: hetzner-k8s
    prometheus:
      existingSecretName: grafana-agent-prometheus-cred
      username_key: username
      password_key: password
      external:
        url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom
metrics:
  enabled: true
  cost:
    enabled: true
  node-exporter:
    enabled: true
traces:
  enabled: true
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: true
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: true
alloy: {}
alloy-events: {}
alloy-logs: {}
