apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicy
metadata:
  name: disable-service-links-workload-policy
spec:
  failurePolicy: Ignore
  reinvocationPolicy: Never
  matchConstraints:
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments", "statefulsets", "daemonsets"]
  matchConditions:
    - name: exclude-kube-system
      expression: "object.metadata.namespace != 'kube-system'"
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: >
          [
            JSONPatch{
              op: "add",
              path: "/spec/template/spec/enableServiceLinks",
              value: false
            }
          ]
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: disable-service-links-workload-policy-binding
spec:
  policyName: disable-service-links-workload-policy
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
