apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    # Example OCI chart
    chart: nginx-gateway-fabric
    repoURL: ghcr.io/nginxinc/charts
    targetRevision: 1.*
    helm:
      releaseName: nginx-gateway-fabric
      valuesObject:
        nginxGateway:
          replicaCount: 3
        service:
          externalTrafficPolicy: Cluster
          annotations:
            # See https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/internal/annotation/load_balancer.go#L12
            load-balancer.hetzner.cloud/name: k8s-worker-gateway-lb
            load-balancer.hetzner.cloud/location: fsn1
            load-balancer.hetzner.cloud/use-private-ip: "true"
            load-balancer.hetzner.cloud/network: "k8s-network"
            # load-balancer.hetzner.cloud/node-selector: # k8s node label
            # load-balancer.hetzner.cloud/health-check-interval:
            # load-balancer.hetzner.cloud/health-check-timeout:
          type: LoadBalancer
          ports:
            - port: 80
              targetPort: http
              protocol: TCP
              appProtocol: http
              name: http
              nodePort: 31080
            - port: 443
              targetPort: https
              appProtocol: https
              protocol: TCP
              nodePort: 31443
              name: https
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/nginx-gateway-fabric/nginx-gateway-fabric
    - name: App-Source
      value: https://github.com/nginxinc/nginx-gateway-fabric/tree/main/charts/nginx-gateway-fabric
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
