apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: nginx-gateway-fabric
    repoURL: ghcr.io/nginxinc/charts/nginx-gateway-fabric
    # targetRevision: 1.*
    helm:
      releaseName: nginx-gateway-fabric
      valuesObject:
        service:
          annotations: {}
          type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx-gateway-fabric
  info:
    - name: "Chart Info"
      value: "https://artifacthub.io/packages/helm/nginx-gateway-fabric/nginx-gateway-fabric"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
