apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.*
    helm:
      releaseName: ingress-nginx
      valuesObject:
        controller:
          name: controller
          kind: DaemonSet # `DaemonSet` or `Deployment`
          service:
            enabled: true
            annotations:
              # See https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/internal/annotation/load_balancer.go#L12
              load-balancer.hetzner.cloud/name: k8s-worker-ingress-lb
              load-balancer.hetzner.cloud/location: fsn1
              load-balancer.hetzner.cloud/use-private-ip: "true"
              load-balancer.hetzner.cloud/network: "k8s-network"
            type: LoadBalancer
            nodePorts:
              http: 32080
              https: 32443
              tcp: {}
              udp: {}
          ingressClassResource:
            name: nginx
            enabled: true
            default: true
          config:
            # use-proxy-protocol: true
            use-http2: true
            use-gzip: true
            server-tokens: false
            enable-opentelemetry: "true"
            otel-service-name: "nginx-proxy" # Opentelemetry resource name
            otlp-collector-host: "grafana-metrics-grafana-agent.monitoring.svc.cluster.local"
            otlp-collector-port: "4317"
            opentelemetry-trust-incoming-span: "true"
            opentelemetry-operation-name: "HTTP $request_method $service_name $uri"
            # opentelemetry-config: "/etc/nginx/opentelemetry.toml"
            # otel-max-queuesize: "2048"
            # otel-schedule-delay-millis: "5000"
            # otel-max-export-batch-size: "512"
            # otel-sampler: "AlwaysOn" # Also: AlwaysOff, TraceIdRatioBased
            # otel-sampler-ratio: "1.0"
            # otel-sampler-parent-based: "false"
          opentelemetry:
            enabled: true
          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/port: "10254"
                prometheus.io/scrape: "true"
        prometheus:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
    - name: App-Source
      value: https://github.com/kubernetes/ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
