apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: argo-events
  name: argo-events-gitlab-watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-read
rules:
  - apiGroups: ["apps.gitlab.com"]
    verbs: [get, list, watch]
    resources: ["*"]
  - apiGroups: ["apps"]
    verbs: [get, list, watch]
    resources: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab-read
subjects:
  - kind: ServiceAccount
    name: argo-events-gitlab-watch
    namespace: argo-events
