apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hcloud
  namespace: cluster-autoscaler
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store # name of the SecretStore (or kind specified)
  target:
    name: hcloud # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        network: k8s-network
        token: "{{ .token }}"
  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: token
      remoteRef:
        key: hcloud-k8s-token
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
