apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hcloud-volumes-encrypted
provisioner: csi.hetzner.cloud
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/node-publish-secret-name: csi-encryption-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: csi-encryption-secret
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: csi-encryption-secret
    creationPolicy: Owner
  data:
    - secretKey: encryption-passphrase
      remoteRef:
        key: github-webhook-secret
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
