apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-cluster-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  source:
    repoURL: https://github.com/hegerdes/GitOps.git
    targetRevision: HEAD
    path: k8s-cluster-hcloud-critical
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
