apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: hello-world
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: hello-world

  # This is a list of basic label selector to select the namespaces to deploy ExternalSecrets to.
  # you can read more about them here https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
  # The list is OR'd together, so if any of the namespaceSelectors match the namespace,
  # the ExternalSecret will be deployed to that namespace.
  namespaceSelectors:
    - matchLabels:
        color: green

  # How often the ClusterExternalSecret should reconcile itself
  # This will decide how often to check and make sure that the ExternalSecrets exist in the matching namespaces
  refreshTime: "5m"

  # This is the spec of the ExternalSecrets to be created
  # The content of this was taken from our ExternalSecret example
  externalSecretSpec:
    secretStoreRef:
      name: azure-store
      kind: ClusterSecretStore

    refreshInterval: "1h"
    target:
      name: hello-world
      creationPolicy: Merge
      template:
        type: Opaque
        # data:
        #   config.yml: |
        #     endpoints:
        #     - https://{{ .data.user }}:{{ .data.password }}@api.exmaple.com
        # templateFrom:
        #   - configMap:
        #       name: alertmanager
        #       items:
        #         - key: alertmanager.yaml
    data:
      - secretKey: data1
        remoteRef:
          key: github-oauth-demo-cookie-secret
          decodingStrategy: None # can be None, Base64, Base64URL or Auto
