apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mimir-azure-storage-creds
  namespace: mimir
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store # name of the SecretStore (or kind specified)
  target:
    name: mimir-azure-storage-creds # name of the k8s Secret to be created
    creationPolicy: Owner
  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: azure_storage_account_key
      remoteRef:
        key: mimir-azure-sa-key
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
