apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mimir-s3-storage-creds
  namespace: mimir
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store # name of the SecretStore (or kind specified)
  target:
    name: mimir-s3-storage-creds # name of the k8s Secret to be created
    creationPolicy: Owner
  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: hcloud-k8s-testing-s3-key-id
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: hcloud-k8s-testing-s3-access-key
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
