apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hcloud-scale-conf
  namespace: cluster-autoscaler
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: hcloud-scale-conf
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        ssh-key: dummy-key
        cluster-config: "{{ .clusterconfig }}"
  data:
    - secretKey: clusterconfig
      remoteRef:
        key: k8s-hetzner-custer-autoscale-conf
        # TODO: set to Base64 once https://github.com/kubernetes/autoscaler/pull/7817 os released
        decodingStrategy: Auto # can be None, Base64, Base64URL or Auto
