apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hcloud-scale-conf
  namespace: cluster-autoscaler
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store # name of the SecretStore (or kind specified)
  target:
    name: hcloud-scale-conf # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        ssh-key: dummy-key
        cluster-config: "{{ .cluster-config }}"
  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: cluster-config
      remoteRef:
        key: talos-hetzner-custer-autoscale-conf
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
