apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: certmanager-dns-cloudflare
  namespace: nginx-gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: certmanager-dns-cloudflare
    creationPolicy: Owner
  data:
    - secretKey: apiToken
      remoteRef:
        key: cloudflare-dns-henrikgerdes-me
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
