apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.*
    helm:
      releaseName: loki
      valuesObject:
        # helm template loki grafana/loki -f loki-values.yml -n loki
        deploymentMode: SimpleScalable # can be SingleBinary, SimpleScalable, Distributed
        global:
          extraArgs:
            - "-config.expand-env=true"
          extraEnv:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-s3-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-s3-creds
                  key: AWS_SECRET_ACCESS_KEY
        loki:
          ingester:
            chunk_encoding: snappy
          rulerConfig:
            external_url: https://grafana.k8s.henrikgerdes.me
          schemaConfig:
            configs:
              - from: 2024-04-01
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage:
            object_store:
              storage_prefix: k8s-loki
            bucketNames:
              chunks: hegerdes-monitoring
              ruler: hegerdes-monitoring
              admin: hegerdes-monitoring
            type: s3
            s3:
              region: weur
              endpoint: f8dcb6c50cc8b86dcf6953a50c3bf736.r2.cloudflarestorage.com
              accessKeyId: "${AWS_ACCESS_KEY_ID}"
              secretAccessKey: "${AWS_SECRET_ACCESS_KEY}"
          limits_config:
            allow_structured_metadata: true

          # structuredConfig:
          #   ruler:
          #     alertmanager_url: http://lgtm-mimir-alertmanager:8080
          #     enable_alertmanager_v2: true
          gateway:
            ingress:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: "letsencrypt-prod-ing-nginx"
              # # Basic auth for now
              # nginx.ingress.kubernetes.io/auth-type: "basic"
              # nginx.ingress.kubernetes.io/auth-secret: "monitoring-auth"
            hosts:
              - host: loki.k8s.henrikgerdes.me
                paths:
                  - path: /
            tls:
              - secretName: loki-gateway-tls
                hosts:
                  - loki.k8s.henrikgerdes.me

        minio:
          enabled: false

        backend:
          replicas: 3
          annotations:
            secret.reloader.stakater.com/reload: "loki-s3-creds"
        read:
          replicas: 3
          annotations:
            secret.reloader.stakater.com/reload: "loki-s3-creds"
          persistence:
            size: 20Gi
        write:
          replicas: 3
          annotations:
            secret.reloader.stakater.com/reload: "loki-s3-creds"
          persistence:
            size: 20Gi

        lokiCanary:
          enabled: false
        test:
          enabled: false
        chunksCache:
          allocatedMemory: 2048

        extraObjects:
          - apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: loki-s3-creds
            spec:
              refreshInterval: 1h
              secretStoreRef:
                kind: ClusterSecretStore
                name: azure-store
              target:
                name: loki-s3-creds
                creationPolicy: Owner

              data:
                - secretKey: AWS_ACCESS_KEY_ID
                  remoteRef:
                    key: cloudflare-r2-monitoring-key-id
                    decodingStrategy: None # can be None, Base64, Base64URL or Auto
                - secretKey: AWS_SECRET_ACCESS_KEY
                  remoteRef:
                    key: cloudflare-r2-monitoring-secret-key
                    decodingStrategy: None # can be None, Base64, Base64URL or Auto

  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  info:
    - name: Chart Info
      value: https://artifacthub.io/packages/helm/grafana/loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
