apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    - chart: tailscale-operator
      repoURL: https://pkgs.tailscale.com/helmcharts
      targetRevision: 1.*
      helm:
        releaseName: tailscale
        valuesObject:
          apiServerProxyConfig:
            mode: "noauth" # "true", "false", "noauth"

    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-cluster-hcloud-critical/tailscale
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  info:
    - name: Chart-Info
      value: https://pkgs.tailscale.com/helmcharts/index.yaml
    - name: Tailscale Operator Docs
      value: https://tailscale.com/kb/1236/kubernetes-operator
    - name: App-Source
      value: https://github.com/tailscale/tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
