apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  project: default
  sources:
    - chart: oauth2-proxy
      repoURL: https://oauth2-proxy.github.io/manifests
      targetRevision: 7.*
      helm:
        releaseName: oauth2-proxy
        valuesObject:
          config:
            existingSecret: oauth2-client-conf
            sessionStorage:
              type: redis
              redis:
                existingSecret: oauth2-redis
                standalone:
                  connectionUrl: "redis://oauth2-redis-master:6379"
            configFile: |
              provider = "github"
              email_domains = [ "*" ]
              upstreams = [ "file:///dev/null" ]
              scope = "oidc user"
              cookie_domains = ".k8s.henrikgerdes.me"
              show_debug_on_error = "true"
              skip_provider_button = "true"
              pass_access_token = "true"
              pass_authorization_header = "true"
              whitelist_domains = ".k8s.henrikgerdes.me"
          ingress:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
            path: /oauth2
            pathType: Prefix
            hosts:
              - oauth.k8s.henrikgerdes.me
            tls:
              - hosts:
                  - oauth.k8s.henrikgerdes.me
                secretName: oauth2-proxy-cert-ing
    - chart: redis
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 20.*
      helm:
        releaseName: oauth2-redis
        valuesObject:
          architecture: standalone
          master:
            kind: Deployment
            persistence:
              enabled: false
              medium: ""
              sizeLimit: 2Gi
    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-apps/oauth2-proxy
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: oauth-proxy
  info:
    - name: Chart-Info Redis
      value: https://artifacthub.io/packages/helm/bitnami/redis
    - name: Chart-Info OAuth2
      value: https://artifacthub.io/packages/helm/oauth2-proxy/oauth2-proxy
    - name: App-Source
      value: https://github.com/oauth2-proxy/oauth2-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
