apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    name: grafana
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 10.*
    helm:
      releaseName: grafana
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod-ing-nginx
          hosts: [grafana.k8s.henrikgerdes.me]
          tls:
            - secretName: grafana-ingress
              hosts:
                - grafana.k8s.henrikgerdes.me
        route:
          main:
            enabled: true
            hostnames: [grafana.k8s-gw.henrikgerdes.me]
            parentRefs:
              # - name: nginx-default-gateway
              #   namespace: nginx-gateway
              - name: cilium-gateway
                namespace: cilium-gateway
                kind: Gateway
                group: gateway.networking.k8s.io
        envFromSecret: grafana-secret-sso-entra
        plugins:
          - digrich-bubblechart-panel
          - grafana-clock-panel
        grafana.ini:
          auth:
            disable_login_form: true
          auth.azuread:
            name: Microsoft SSO
            enabled: true
            allow_sign_up: true
            auto_login: false
            scopes: openid email profile
            auth_url: https://login.microsoftonline.com/295b5ac3-2e4e-4ade-85d8-7dc31617bc2c/oauth2/v2.0/authorize
            token_url: https://login.microsoftonline.com/295b5ac3-2e4e-4ade-85d8-7dc31617bc2c/oauth2/v2.0/token
            allowed_organizations: 295b5ac3-2e4e-4ade-85d8-7dc31617bc2c
            role_attribute_strict: false
            allow_assign_grafana_admin: true
            skip_org_role_sync: false
            use_pkce: true
          # auth.github:
          #   enabled: true
          #   allow_sign_up: false
          #   auto_login: false
          #   scopes: user:email,read:org
          #   auth_url: https://github.com/login/oauth/authorize
          #   token_url: https://github.com/login/oauth/access_token
          #   api_url: https://api.github.com/user
          #   allowed_organizations: DemeterPlanet
          # team_ids:
          # client_id: # done via env mounted via secret
          # client_secret: # done via env mounted via secret
          # auth.gitlab:
          #   enabled: true
          #   allow_sign_up: true
          #   allow_assign_grafana_admin: true
          #   scopes: openid email profile
          #   auth_url: https://gitlab.com/oauth/authorize
          #   token_url: https://gitlab.com/oauth/token
          #   api_url: https://gitlab.com/api/v4
          #   role_attribute_path: contains(groups[*], 'demo/devops') && 'Admin' || contains(groups[*], 'demo/dev') && 'Viewer'
          analytics:
            check_for_updates: true
          log:
            mode: console
          grafana_net:
            url: https://grafana.net
          server:
            # domain: grafana.k8s-gw.henrikgerdes.me
            # root_url: https://grafana.k8s-gw.henrikgerdes.me
            domain: grafana.k8s.henrikgerdes.me
            root_url: https://grafana.k8s.henrikgerdes.me
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: "default"
                orgId: 1
                folder: ""
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards
              - name: "kubernetes-dashboards"
                orgId: 1
                folder: "Kubernetes"
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/kubernetes
              - name: "custom-dashboards"
                orgId: 1
                folder: "Custom"
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/custom
        dashboards:
          default:
            cert-manager:
              gnetId: 11001
              revision: 1
              datasource: Mimir

            nginx-ingress:
              gnetId: 9614
              revision: 1
              datasource: Mimir

            node-exporter:
              gnetId: 1860
              revision: 37
              datasource: Mimir
              # https://grafana.com/grafana/dashboards/1860-node-exporter-full/

            argocd:
              gnetId: 14584
              revision: 1
              datasource: Mimir
              # https://grafana.com/grafana/dashboards/14584-argocd/

            prometheus-stats:
              gnetId: 2
              revision: 2
              datasource: Mimir

            cnpg:
              url: https://raw.githubusercontent.com/cloudnative-pg/grafana-dashboards/refs/heads/main/charts/cluster/grafana-dashboard.json
              datasource: Mimir

            kube-overview:
              gnetId: 18283
              revision: 1
              datasource: Mimir

          kubernetes-dashboards:
            k8s-apiserver:
              url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
              datasource: Mimir

            k8s-coredns:
              url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
              datasource: Mimir

            k8s-etcd:
              gnetId: 15308 # https://grafana.com/grafana/dashboards/15308-etcd-cluster-overview/
              revision: 1
              datasource: Mimir

            k8s-global-1:
              gnetId: 14623 # https://grafana.com/grafana/dashboards/14623-kubernetes-monitoring-overview/
              revision: 1
              datasource: Mimir

            k8s-global-2:
              url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
              datasource: Mimir

            k8s-namespaces:
              url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
              datasource: Mimir

            k8s-nodes-view:
              url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
              datasource: Mimir

            k8s-pods-view:
              url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
              datasource: Mimir
        # datasources:
        #   datasources.yaml:
        #     apiVersion: 1
        #     datasources:
        #       - name: Prometheus
        #         type: prometheus
        #         url: https://prometheus-k8s.monitoring.svc.cluster.local:9091
        #         access: proxy
        #         isDefault: true
        #         editable: true
        #         jsonData:
        #           tlsAuthWithCACert: true
        #           httpHeaderName1: "Authorization"
        #         secureJsonData:
        #           # tlsCACert: |
        #           httpHeaderValue1: Bearer $OKD_PROMETHEUS_TOKEN
        extraObjects:
          - apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: grafana-secret-sso-gh
            spec:
              refreshInterval: 1h
              secretStoreRef:
                kind: ClusterSecretStore
                name: azure-store
              target:
                name: grafana-secret-sso-gh
                creationPolicy: Owner
              data:
                - secretKey: GF_AUTH_GITHUB_CLIENT_ID
                  remoteRef:
                    key: github-oauth-argocd-client-id
                    decodingStrategy: None # can be None, Base64, Base64URL or Auto
                - secretKey: GF_AUTH_GITHUB_CLIENT_SECRET
                  remoteRef:
                    key: github-oauth-argocd-secret
                    decodingStrategy: None # can be None, Base64, Base64URL or Auto
          - apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: grafana-secret-sso-entra
            spec:
              refreshInterval: 1h
              secretStoreRef:
                kind: ClusterSecretStore
                name: azure-store
              target:
                name: grafana-secret-sso-entra
                creationPolicy: Owner
              data:
                - secretKey: GF_AUTH_AZUREAD_CLIENT_ID
                  remoteRef:
                    key: aad-testing-client-id
                    decodingStrategy: None # can be None, Base64, Base64URL or Auto
                - secretKey: GF_AUTH_AZUREAD_CLIENT_SECRET
                  remoteRef:
                    key: aad-testing-client-secret
                    decodingStrategy: None # can be None, Base64, Base64URL or Auto
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/grafana/grafana
    - name: App-Docs
      value: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
    - name: App-Source
      value: https://github.com/grafana/grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
