apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.*
    helm:
      releaseName: longhorn
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
        longhornUI:
          replicas: 1
        ingress:
          enabled: true
          host: longhorn.k8s.henrikgerdes.me
          ingressClassName: nginx
          tls: true
          tlsSecret: longhorn-ui-public
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
            # nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.oauth-proxy.svc.cluster.local/oauth2/auth
            # nginx.ingress.kubernetes.io/auth-signin: https://oauth.k8s.henrikgerdes.me/oauth2/start?rd=https://$host$request_uri
            # nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, X-Auth-Request-Email, X-Auth-Request-User, X-Auth-Request-Access-Token"

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/longhorn/longhorn
    - name: App-Source
      value: https://github.com/longhorn/longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
