apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - chart: crossplane
      repoURL: https://charts.crossplane.io/stable
      targetRevision: 1.*
      helm:
        releaseName: crossplane
        valuesObject:
          provider:
            packages:
              - xpkg.upbound.io/upbound/provider-terraform:v0
              - xpkg.upbound.io/upbound/provider-aws-s3:v1
              # - xpkg.upbound.io/upbound/provider-family-azure:v1.10.0
              # - xpkg.upbound.io/upbound/provider-family-aws:v1.18.0
              # - xpkg.upbound.io/coopnorge/provider-github:v0.13.0
          extraObjects: []
          # - apiVersion: pkg.crossplane.io/v1
          #   kind: Provider
          #   metadata:
          #     name: provider-family-azure
          #   spec:
          #     package: xpkg.upbound.io/upbound/provider-family-azure:v1.4.0

    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-apps/crossplane
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/crossplane/crossplane
  syncPolicy:
    # preserveResourcesOnDeletion: true
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
