apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
spec:
  project: default
  sources:
    - chart: nginx-gateway-fabric
      repoURL: ghcr.io/nginx/charts
      targetRevision: 2.*
      helm:
        releaseName: nginx-gateway-fabric
        valuesObject:
          nginxGateway:
            replicas: 1
          # A list of Gateway objects. View https://gateway-api.sigs.k8s.io/reference/spec/#gateway
          # https://cert-manager.io/docs/usage/gateway/
          gateways: []
    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-apps/nginx-gateway-fabric
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/nginx-gateway-fabric/nginx-gateway-fabric
    - name: App-Source
      value: https://github.com/nginxinc/nginx-gateway-fabric/tree/main/charts/nginx-gateway-fabric
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
