apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    - chart: argo-events
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 2.*
      helm:
        releaseName: argo-events
        valuesObject:
          extraObjects:
            - apiVersion: argoproj.io/v1alpha1
              kind: EventBus
              metadata:
                name: default
              spec:
                nats:
                  native:
                    replicas: 3 # 3 is minimal
                    auth: none # Optional, authen strategy, "none" or "token", defaults to "none"
              #      containerTemplate:
              #        resources:
              #          requests:
              #            cpu: "10m"
              #      metricsContainerTemplate:
              #        resources:
              #          requests:
              #            cpu: "10m"
              #      antiAffinity: false
              #      persistence:
              #        storageClassName: standard
              #        accessMode: ReadWriteOnce
              #        volumeSize: 10Gi
    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-apps/argo-events
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/argo/argo-events
    - name: App-Source
      value: https://github.com/argoproj/argo-events
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
