apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cluster-autoscaler
      repoURL: https://kubernetes.github.io/autoscaler
      targetRevision: 9.*
      helm:
        releaseName: k8s-scaler
        valuesObject:
          extraArgs:
            max-node-provision-time: 10m0s
            ignore-daemonsets-utilization: "true"
            skip-nodes-with-system-pods: "false"
          cloudProvider: hetzner
          deployment:
            annotations:
              secret.reloader.stakater.com/reload: "hcloud-scale-conf"
          autoDiscovery:
            clusterName: hcloud
          rbac:
            serviceAccount:
              name: cluster-autoscaler
          extraEnv:
            HCLOUD_NETWORK: k8s-network
            HCLOUD_CLUSTER_CONFIG_FILE: /hcloud/conf/cluster-config
          extraVolumes:
            - name: scripts
              configMap:
                name: cluster-scaler-scripts
            - name: scale-conf
              secret:
                secretName: hcloud-scale-conf
          extraVolumeMounts:
            - name: scale-conf
              mountPath: "/hcloud/conf"
              readOnly: true
          extraEnvSecrets:
            HCLOUD_TOKEN:
              name: hcloud
              key: token
            # HCLOUD_CLUSTER_CONFIG:
            #   name: hcloud-scale-conf
            #   key: cluster-config
            HCLOUD_SSH_KEY:
              name: hcloud-scale-conf
              key: ssh-key
          autoscalingGroups:
            - name: cas-arm-small
              maxSize: 2
              minSize: 0
              instanceType: CAX11
              region: FSN1
            - name: cas-amd-small
              maxSize: 2
              minSize: 0
              instanceType: CX22
              region: FSN1
          extraObjects:
    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-apps/cluster-autoscaler
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-autoscaler
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
