apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-sandbox
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/agent-sandbox.git
    targetRevision: HEAD
    path: helm/
    helm:
      releaseName: agent-sandbox
      valuesObject:
        image:
          tag: v0.4.6
        namespace:
          create: false
          name: agent-sandbox
  destination:
    server: https://kubernetes.default.svc
    namespace: agent-sandbox
  info:
    - name: App-Source
      value: https://github.com/kubernetes-sigs/agent-sandbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
