apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: reloader
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 2.*
    helm:
      releaseName: reloader
      valuesObject:
        reloader:
          ignoreJobs: true
          ignoreCronJobs: true
          deployment:
            containerSecurityContext:
              capabilities:
                drop:
                  - ALL
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/stakater/reloader
    - name: App-Source
      value: https://github.com/stakater/Reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
