apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-gateway
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-apps/cilium-gateway
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cilium-gateway
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/cilium/cilium
    - name: App-Docs
      value: https://docs.cilium.io/en/stable/network/kubernetes/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
