apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telepresence
  namespace: argocd
spec:
  project: default
  source:
    chart: telepresence-oss
    repoURL: ghcr.io/telepresenceio
    targetRevision: 2.*
    helm:
      releaseName: telepresence-traffic-manager
      valuesObject: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: telepresence
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/nginx-gateway-fabric/nginx-gateway-fabric
    - name: App-Source
      value: https://github.com/nginxinc/nginx-gateway-fabric/tree/main/charts/nginx-gateway-fabric
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
