apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cluster-autoscaler
      repoURL: https://kubernetes.github.io/autoscaler
      targetRevision: 9.*
      helm:
        releaseName: cluster-autoscaler
        valuesObject:
          cloudProvider: hetzner
          extraEnv:
            HCLOUD_NETWORK: k8s-network
          extraEnvSecrets:
            HCLOUD_TOKEN:
              name: hcloud
              key: token
            HCLOUD_CLUSTER_CONFIG:
              name: hcloud-scale-conf
              key: cluster-config
            HCLOUD_SSH_KEY:
              name: hcloud-scale-conf
              key: ssh-key
          autoscalingGroups:
            - name: cas-arm-small
              maxSize: 2
              minSize: 0
              instanceType: CAX11
              region: FSN1
            - name: cas-amd-small
              maxSize: 2
              minSize: 0
              instanceType: CX22
              region: FSN1
          autoDiscovery:
            clusterName: hcloud
    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-apps/cluster-autoscaler
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-autoscaler
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
