apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  labels:
    name: keda
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.*
    helm:
      releaseName: keda
      valuesObject:
        clusterName: hcloud
        image:
          pullPolicy: IfNotPresent
        prometheus:
          metricServer:
            enabled: false
            serviceMonitor:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/kedacore/keda
    - name: App-Docs
      value: https://keda.sh/docs/
    - name: App-Source
      value: https://github.com/kedacore/keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
