apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - chart: policy-controller
      repoURL: https://sigstore.github.io/helm-charts
      targetRevision: 0.*
      helm:
        releaseName: policy-controller
        valuesObject:
          webhook:
            namespaceSelector:
              matchExpressions:
                - key: webhooks.knative.dev/exclude
                  operator: In
                  values: ["true"]
                - key: policy.sigstore.dev/include
                  operator: In
                  values: ["true"]
    - repoURL: https://github.com/hegerdes/GitOps.git
      targetRevision: HEAD
      path: k8s-apps/policy-controller
      directory:
        recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cosign-system
  info:
    - name: "Chart Info"
      value: "https://artifacthub.io/packages/helm/sigstore/policy-controller"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - kind: MutatingWebhookConfiguration
      group: "admissionregistration.k8s.io"
      jqPathExpressions:
        - .webhooks[].namespaceSelector
    - kind: ValidatingWebhookConfiguration
      group: "admissionregistration.k8s.io"
      jqPathExpressions:
        - .webhooks[].namespaceSelector
  # - group: "*"
  #   kind: "*"
  #   managedFieldsManagers:
  #   - kube-controller-manager
