apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.*
    helm:
      releaseName: sealed-secrets
      valuesObject:
        secretName: kubeseal-key
        extraDeploy:
          - apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: kubeseal-key
              namespace: sealed-secrets
            spec:
              refreshInterval: 6h
              secretStoreRef:
                kind: ClusterSecretStore
                name: azure-store
              target:
                name: kubeseal-key
                creationPolicy: Owner
                template:
                  type: kubernetes.io/tls
                  metadata:
                    labels:
                      sealedsecrets.bitnami.com/sealed-secrets-key: active
              data:
                # Decoding strategy can be None, Base64, Base64URL or Auto
                - secretKey: tls.crt
                  remoteRef:
                    key: k8s-kubeseal-demo-cert
                    decodingStrategy: Auto
                - secretKey: tls.key
                  remoteRef:
                    key: k8s-kubeseal-demo-key
                    decodingStrategy: Auto
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  info:
    - name: Chart-Info
      value: https://artifacthub.io/packages/helm/bitnami-labs/sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
