apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-mix
  namespace: argocd
  labels:
    name: workload-mix
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://github.com/hegerdes/GitOps.git
    targetRevision: HEAD
    path: k8s-apps/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: wasm
  info:
    - name: Example Link
      value: https://example.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
