apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-scheduler
  labels:
    component: kube-scheduler
    tier: control-plane
    app: kube-scheduler
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kube-scheduler
      tier: control-plane
      app: kube-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        component: kube-scheduler
        tier: control-plane
        app: kube-scheduler
    spec:
      enableServiceLinks: false
      containers:
        - name: kube-scheduler
          image: registry.k8s.io/kube-scheduler:v1.35.0
          imagePullPolicy: IfNotPresent
          # Docs: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
          command:
            - kube-scheduler
            - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
            - --authentication-kubeconfig=/etc/kubernetes/kubeconfig.yml
            - --authorization-kubeconfig=/etc/kubernetes/kubeconfig.yml
            - --kubeconfig=/etc/kubernetes/kubeconfig.yml
            - --leader-elect=true
            - --profiling=false
            - --secure-port=10259
            - --tls-min-version=VersionTLS13
            - --tls-cert-file=/etc/kubernetes/pki/tls.crt
            - --tls-private-key-file=/etc/kubernetes/pki/tls.key
            - --client-ca-file=/etc/kubernetes/pki/kube-ca.crt
            - --leader-elect-resource-namespace=default
          ports:
            - containerPort: 10259
              name: scheduler-port
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop: [all]
              add: ["NET_BIND_SERVICE"]
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /livez
              port: scheduler-port
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: scheduler-port
              scheme: HTTPS
            periodSeconds: 1
            timeoutSeconds: 15
          resources:
            requests:
              cpu: 100m
          startupProbe:
            failureThreshold: 24
            httpGet:
              path: /livez
              port: scheduler-port
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 15
          volumeMounts:
            - mountPath: /etc/kubernetes
              name: kubeconfig
              readOnly: true
            - mountPath: /etc/kubernetes/pki
              name: tls-kube
              readOnly: true
      # priority: 2000001000
      # priorityClassName: system-node-critical
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
        - name: kubeconfig
          projected:
            sources:
              - secret:
                  name: kube-scheduler-client-tls
                  items:
                    - key: ca.crt
                      path: ca.crt
                    - key: tls.crt
                      path: kube.crt
                    - key: tls.key
                      path: kube.key
              - configMap:
                  name: kubeconf-template
                  items:
                    - key: kubeconfig.yml
                      path: kubeconfig.yml
        - name: tls-kube
          projected:
            sources:
              - secret:
                  name: kube-front-proxy-client-tls
                  items:
                    - key: ca.crt
                      path: front-proxy-ca.crt
              - secret:
                  name: kube-scheduler-serving-tls
                  items:
                    - key: ca.crt
                      path: kube-ca.crt
                    - key: tls.crt
                      path: tls.crt
                    - key: tls.key
                      path: tls.key
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-scheduler
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
spec:
  ports:
    - port: 10259
      protocol: TCP
      targetPort: scheduler-port
      name: scheduler-port
  selector:
    app: kube-scheduler
    component: kube-scheduler
    tier: control-plane
