apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  labels:
    app: etcd
    component: etcd
    tier: control-plane
spec:
  serviceName: etcd
  replicas: 1
  selector:
    matchLabels:
      app: etcd
      component: etcd
      tier: control-plane
  template:
    metadata:
      labels:
        app: etcd
        component: etcd
        tier: control-plane
    spec:
      hostname: etcd
      enableServiceLinks: false
      initContainers:
        - name: create-conf
          image: alpine
          command:
            - /scripts/generate-conf.sh
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - mountPath: /etc/etcd
              name: share
            - mountPath: /scripts
              name: scripts
      containers:
        - name: etcd
          image: registry.k8s.io/etcd:3.6.7-0
          command: [etcd, --config-file=/etc/etcd/etcd-conf.yaml]
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /livez
              port: probe-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: probe-port
              scheme: HTTP
            periodSeconds: 1
            timeoutSeconds: 15
          startupProbe:
            failureThreshold: 24
            httpGet:
              path: /readyz
              port: probe-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 15
          ports:
            - containerPort: 2381
              name: probe-port
              protocol: TCP
            - containerPort: 2380
              name: peer-port
              protocol: TCP
            - containerPort: 2379
              name: client-port
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /var/lib/etcd
              name: etcd-data
            - mountPath: /etc/kubernetes/pki/etcd
              name: tls-etcd
            - mountPath: /etc/etcd
              name: share
      # priority: 2000001000
      # priorityClassName: system-node-critical
      # securityContext:
      #   seccompProfile:
      #     type: RuntimeDefault
      volumes:
        - name: share
          emptyDir:
            sizeLimit: 10Mi
        - name: scripts
          configMap:
            name: etcd-scripts
            defaultMode: 0755
        - name: tls-etcd
          projected:
            sources:
              - secret:
                  name: etcd-ca-tls
                  items:
                    - key: tls.crt
                      path: ca.crt
              - secret:
                  name: etcd-server-tls
                  items:
                    - key: tls.crt
                      path: server.crt
                    - key: tls.key
                      path: server.key
              - secret:
                  name: etcd-peer-tls
                  items:
                    - key: tls.crt
                      path: peer.crt
                    - key: tls.key
                      path: peer.key
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
    component: etcd
    tier: control-plane
spec:
  clusterIP: None
  ports:
    - name: clients
      port: 2379
      targetPort: client-port
  selector:
    app: etcd
    component: etcd
    tier: control-plane
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-scripts
data:
  generate-conf.sh: |
    #!/bin/sh

    # This is the configuration file for the etcd server
    # Full example: https://github.com/etcd-io/etcd/blob/main/etcd.conf.yml.sample
    cat > /etc/etcd/etcd-conf.yaml <<EOF
    # This is the configuration file for the etcd server

    # Human-readable name for this member.
    name: $POD_NAME

    # Path to the data directory.
    data-dir: /var/lib/etcd

    # Number of committed transactions to trigger a snapshot to disk.
    snapshot-count: 10000

    # Time (in milliseconds) of a heartbeat interval.
    heartbeat-interval: 100

    # Time (in milliseconds) for an election to timeout.
    election-timeout: 1000

    # List of comma separated URLs to listen on for peer traffic.
    listen-peer-urls: https://$POD_IP:2380

    # List of comma separated URLs to listen on for client traffic.
    listen-client-urls: https://$POD_IP:2379

    # Maximum number of snapshot files to retain (0 is unlimited).
    max-snapshots: 200

    # Maximum number of wal files to retain (0 is unlimited).
    max-wals: 200

    # List of this member's client URLs to advertise to the public.
    # The URLs needed to be a comma-separated list.
    advertise-client-urls: https://$POD_IP:2379

    listen-metrics-urls: http://$POD_IP:2381

    # Valid values include 'on', 'readonly', 'off'
    proxy: 'off'

    client-transport-security:
      # Path to the client server TLS cert file.
      cert-file: /etc/kubernetes/pki/etcd/server.crt

      # Path to the client server TLS key file.
      key-file: /etc/kubernetes/pki/etcd/server.key

      # Enable client cert authentication.
      client-cert-auth: true

      # Path to the client server TLS trusted CA cert file.
      trusted-ca-file: /etc/kubernetes/pki/etcd/ca.crt

      # Client TLS using generated certificates
      auto-tls: false

    peer-transport-security:
      # Path to the peer server TLS cert file.
      cert-file: /etc/kubernetes/pki/etcd/peer.crt

      # Path to the peer server TLS key file.
      key-file: /etc/kubernetes/pki/etcd/peer.key

      # Enable peer client cert authentication.
      client-cert-auth: true

      # Path to the peer server TLS trusted CA cert file.
      trusted-ca-file: /etc/kubernetes/pki/etcd/ca.crt

      # Peer TLS using generated certificates.
      auto-tls: false

    # Enable debug-level logging for etcd.
    log-level: info

    # Specify 'stdout' or 'stderr' to skip journald logging even when running under systemd.
    log-outputs: [stdout]

    # Force to create a new one member cluster.
    force-new-cluster: false

    auto-compaction-mode: periodic
    auto-compaction-retention: "1"

    # Limit etcd to specific TLS protocol versions
    tls-min-version: 'TLS1.3'
    EOF

    cat /etc/etcd/etcd-conf.yaml
