apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-client
spec:
  secretName: argocd-client-tls
  commonName: argocd-client
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - client auth
  privateKey:
    algorithm: RSA
    size: 2048
  subject:
    organizationalUnits:
      - argocd-auth
    organizations:
      - kubernetes
  dnsNames: []
  emailAddresses:
    - kubernetes-pki@hegerdes.com
  issuerRef:
    name: ca-kube-controlplane
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-downstream-api-proxy
spec:
  secretName: kube-downstream-api-proxy-tls
  commonName: kube-haproxy
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  additionalOutputFormats:
  - type: CombinedPEM
  usages:
    - digital signature
    - key encipherment
    - server auth
  privateKey:
    algorithm: RSA
    size: 2048
  subject:
    organizationalUnits:
      - kube-haproxy
    organizations:
      - kubernetes
  dnsNames:
    - "kubernetes"
    - "kubernetes.default"
    - "kubernetes.default.svc"
    - "kubernetes.default.svc.cluster.local"
  ipAddresses:
    - "{{ .Values.controlplane.inClusterIP }}"  #
    - "10.96.0.1"   # cluster service ip
  emailAddresses:
    - kubernetes-pki@hegerdes.com
  issuerRef:
    name: ca-kube-controlplane
    kind: Issuer
