apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  labels:
    app: etcd
    component: etcd
    tier: control-plane
spec:
  serviceName: etcd
  replicas: 1
  selector:
    matchLabels:
      app: etcd
      component: etcd
      tier: control-plane
  template:
    metadata:
      labels:
        app: etcd
        component: etcd
        tier: control-plane
    spec:
      hostname: etcd
      enableServiceLinks: false
      initContainers:
        - name: create-conf
          image: alpine
          command:
            - /scripts/generate-conf.sh
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - mountPath: /etc/etcd
              name: share
            - mountPath: /scripts
              name: scripts
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
      containers:
        - name: etcd
          image: registry.k8s.io/etcd:3.6.7-0
          command: [etcd, --config-file=/etc/etcd/etcd-conf.yaml]
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /livez
              port: probe-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: probe-port
              scheme: HTTP
            periodSeconds: 1
            timeoutSeconds: 15
          startupProbe:
            failureThreshold: 24
            httpGet:
              path: /readyz
              port: probe-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 15
          ports:
            - containerPort: 2381
              name: probe-port
              protocol: TCP
            - containerPort: 2380
              name: peer-port
              protocol: TCP
            - containerPort: 2379
              name: client-port
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /var/lib/etcd
              name: etcd-data
            - mountPath: /etc/kubernetes/pki/etcd
              name: tls-etcd
            - mountPath: /etc/etcd
              name: share
      # priority: 2000001000
      # priorityClassName: system-node-critical
      # securityContext:
      #   seccompProfile:
      #     type: RuntimeDefault
      volumes:
        - name: share
          emptyDir:
            sizeLimit: 10Mi
        - name: scripts
          configMap:
            name: etcd-configs
            defaultMode: 0755
        - name: tls-etcd
          projected:
            sources:
              - secret:
                  name: etcd-ca-tls
                  items:
                    - key: tls.crt
                      path: ca.crt
              - secret:
                  name: etcd-server-tls
                  items:
                    - key: tls.crt
                      path: server.crt
                    - key: tls.key
                      path: server.key
              - secret:
                  name: etcd-peer-tls
                  items:
                    - key: tls.crt
                      path: peer.crt
                    - key: tls.key
                      path: peer.key
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
    component: etcd
    tier: control-plane
spec:
  clusterIP: None
  ports:
    - name: clients
      port: 2379
      targetPort: client-port
  selector:
    app: etcd
    component: etcd
    tier: control-plane
