apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    hks.hegerdes.com/managed-cluster: "true"
    {{- with .Values.namespaceLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec: {}
