{{- if .Values.controlplane.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-apiserver
spec:
  minAvailable: 1
  selector:
    matchLabels:
    app: kube-apiserver
    component: kube-apiserver
    tier: control-plane
{{- end }}
