apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    tier: control-plane
  name: kubeconf-template
data:
  kubeconfig.yml: |
    apiVersion: v1
    kind: Config
    current-context: kubernetes@default
    contexts:
      - context:
          cluster: default
          user: default
        name: kubernetes@default
    clusters:
      - cluster:
          certificate-authority: /etc/kubernetes/ca.crt
          server: https://kube-apiserver:6443
        name: default
    users:
      - name: default
        user:
          client-certificate: /etc/kubernetes/kube.crt
          client-key: /etc/kubernetes/kube.key

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-api-configs
data:
  authentication-conf.yaml: |
    # Docs: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens
    apiVersion: apiserver.config.k8s.io/v1beta1
    kind: AuthenticationConfiguration
    anonymous:
      enabled: true
      conditions:
        # kubeadm also needs to read the discovery info:
        - path: /api/v1/namespaces/kube-public/configmaps/cluster-info
        # for status checks:
        - path: /healthz
        - path: /readyz
        - path: /livez
    jwt: []
  authorization-conf.yaml: |
    # Docs: https://kubernetes.io/docs/reference/access-authn-authz/authorization/
    apiVersion: apiserver.config.k8s.io/v1
    kind: AuthorizationConfiguration
    authorizers:
      - type: Node
        name: node
      - type: RBAC
        name: rbac
  audit-policy.yaml: |
    apiVersion: audit.k8s.io/v1
    kind: Policy

    # Don't log the initial RequestReceived stage to cut down on volume
    omitStages:
      - RequestReceived

    # The rules are evaluated in order; the first matching rule applies.
    rules:
      # The following requests were manually identified as high-volume and low-risk,so drop them.
      - level: None
        users: ["system:kube-proxy"]
        verbs: ["watch", "get"]
        resources:
          - group: "" # core
            resources: ["endpoints", "services", "services/status"]
      - level: None
        userGroups: ["system:nodes"]
        verbs: ["get", "watch"]
        resources:
          - group: "" # core
            resources: ["nodes", "nodes/status"]
      - level: None
        users:
          - system:kube-controller-manager
          - system:kube-scheduler
          - system:serviceaccount:kube-system:endpoint-controller
        verbs: ["get", "update", "watch"]
        namespaces: ["kube-system"]
        resources:
          - group: "" # core
            resources: ["endpoints"]
      - level: None
        users: ["system:apiserver"]
        verbs: ["get", "watch"]
        resources:
          - group: "" # core
            resources: ["namespaces", "namespaces/status", "namespaces/finalize"]
      # Don't log HPA fetching metrics.
      - level: None
        users:
          - system:kube-controller-manager
        verbs: ["get", "list"]
        resources:
          - group: "metrics.k8s.io"
      # Don't log these read-only URLs.
      - level: None
        nonResourceURLs:
          - /healthz*
          - /version
          - /swagger*
          - "/metrics"
          - "/openapi*"
      # Don't log events requests.
      - level: None
        resources:
          - group: "" # core
            resources: ["events"]
      # Secrets, TokenRequest and TokenReviews can contain sensitive & binary data,
      # so only log at the Metadata level.
      - level: Metadata
        resources:
          - group: "" # core
            resources: ["secrets", "serviceaccounts/token"]
          - group: authentication.k8s.io
            resources: ["tokenreviews"]

      # Log request+response bodies for any mutating action
      - level: RequestResponse
        verbs: ["create", "update", "patch", "delete"]
        # userGroups: [oidc:]

      # Log metadata only for all other resource requests
      - level: Metadata

      # (Optional) If you have custom API groups you care about, you can add them here
      # - level: RequestResponse
      #   resources:
      #     - group: "myorg.example.com"
      #       resources: ["widgets","gadgets"]

  admission-control-config.yaml: |
    apiVersion: apiserver.config.k8s.io/v1
    kind: AdmissionConfiguration
    plugins:
      - name: PodSecurity # Enable the built-in Pod Security admission plugin
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1
          kind: PodSecurityConfiguration

          # --------------------------------------------------------------------
          # 1. Cluster-wide defaults
          # --------------------------------------------------------------------
          defaults:
            # Reject any pod that violates the baseline profile
            enforce: "baseline"
            enforce-version: "latest"

            # Log (audit) and warn on anything that would break the stricter
            # restricted profile so you can spot future hardening issues early
            audit: "restricted"
            audit-version: "latest"
            warn: "restricted"
            warn-version: "latest"

          # --------------------------------------------------------------------
          # 2. Exemptions for critical system components
          # --------------------------------------------------------------------
          exemptions:
            usernames: [] # (add human break-glass accounts if required)
            runtimeClasses: [] # (e.g. kata-containers, gvisor, etc.)
            namespaces:
              - kube-system # Core control-plane add-ons
              - kube-public # Cluster-info ConfigMap & bootstrap helpers
              - kube-node-lease # Node heart-beat leases
