apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-secrets-store-provider-aws
  namespace: argocd
spec:
  project: default
  source:
    chart: secrets-store-csi-driver-provider-aws
    repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
    targetRevision: 1.*
    helm:
      releaseName: secrets-store-csi-driver-provider-aws
      valuesObject:
        linux:
          podAnnotations:
            cluster-autoscaler.kubernetes.io/enable-ds-eviction: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  info:
    - name: Chart-Info
      value: https://github.com/aws/secrets-store-csi-driver-provider-aws/tree/main/charts/secrets-store-csi-driver-provider-aws
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
