apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secrets-store-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: secrets-store-creds
    creationPolicy: Owner
  data:
    - secretKey: clientid
      remoteRef:
        key: k8s-eso-aad-client-id
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
    - secretKey: clientsecret
      remoteRef:
        key: k8s-eso-aad-client-secret
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
