apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wasm-demo
  namespace: default
spec:
  encryptedData:
    foo: AgCJ9AquWFfH3Zr0owFNzUta2sf8SBXeEF3mmMshZZppqDuRMTpVO4ZcBW4IobON8CKT3PXAUY2c4283/Y0hmekB+Fk3DRTs+u19TRbYBKUODN7RPfu3Yvojju68XH1/Awf3R63h0CRLUCa9Wx6JPTOxV1GnhwkpQbXgW0a2qoOj9yh0zOCuZT3NTWUWa51xUrc3dcVyz1RlbHxwTtbsPtR+J+QifCwkobzFKd0BSJcGxMuJH+DC4Q8WONwwLCmd6q0vhtANEymtt9JNdfwRBU/UxzFLiS6Sr7yhzvDBs3pk77Y8aVD4A4rjF5zr1POx3JrWs842wmh3DfYTJdpty5wAZA8FAg2v8QnWME/wXUP+eE3zgFfolOcMYS99DBwwmNlcPYVYW9nprbU2urTTaGM5wGpGnw5IL7prLUYiMwJEi7bzSiiekYRFToa9DStDYORrjR44JBjImyL9L/SMFotJmVgF5wkrcNXgLMgrRDLyev8q36PEU81i9WZqKMrFBG+P8vSWjr9qr8BlKZjLfU2DmxRKHVNZhlXbqjf7w/TT4ibWZn/RhXUzFBbsMuVQhlFYf8KNVB1FNpcbIVbGmEPtKk5peIXI5MCHAyOInwAT0Ke8krh8+adLV/4W+1SndEgsLiwGy4rcIn8WEQXXuZFiQCjkleFrXjWFVKysYdofXXht3cXkMM1VDTI7CEHaZ9aVPf0=
  template:
    metadata:
      creationTimestamp: null
      name: wasm-demo
      namespace: default
