apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aad-sp-external-dns-azure
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: external-dns-azure
    creationPolicy: Owner

  data:
    - secretKey: azure.json
      remoteRef:
        key: k8s-external-dns-config-azure
        decodingStrategy: Auto # can be None, Base64, Base64URL or Auto
