apiVersion: v2
name: argocd
description: A Meta-Helm-Chart for k8s ArgoCD


type: application
version: 5.36.0
appVersion: "2.7.4"

dependencies:
- name: argocd
  version: 5.36.0
  repository: https://argoproj.github.io/argo-helm
