argocd:
  ## Globally shared configuration
  global:
    # -- Common labels for the all resources
    additionalLabels: {}
    logging:
      format: json # Either: `text` or `json`
      level: info # `debug`, `info`, `warn` or `error`
  ## Server
  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      annotations:
        # cert-manager.io/cluster-issuer: letsencrypt-staging-{{ k8s_ingress_class }}
        cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      ingressClassName: 'nginx'
      hosts:
        - argocd.k8s.henrikgerdes.me
      tls:
        - secretName: argocd-secret
          hosts:
            - argocd.k8s.henrikgerdes.me
      # -- Uses `server.service.servicePortHttps` instead `server.service.servicePortHttp`
      https: false
