kubernetesVersion: v1.36.2
etcdVersion: 3.7.0-0
namespaceLabels: {}
name: default

controlplane:
  domainSuffix: hks.eu-central.hegerdes.com
  publicIp: "publicIpServiceRef"
  publicIpServiceRef:
    namespace: cilium-gateway
    name: cilium-gateway-cilium-gateway
  tlsRoute:
    enabled: true
    gatewayName: hks-gateway
    gatewayNamespace: envoy-gateway
  pdb:
    enabled: false
  konnectivityServer:
    enabled: true

extensions: {}
extraObjects: []
