kubernetesVersion: v1.36.2
etcdVersion: 3.6.11-0
namespaceLabels: {}

controlplane:
  domainSuffix: hks.eu-central.hegerdes.com
  publicIp: "publicIpServiceRef"
  publicIpServiceRef:
    namespace: cilium-gateway
    name: cilium-gateway-cilium-gateway
  tlsRoute:
    enabled: true
    gatewayName: hks-gateway
    gatewayNamespace: envoy-gateway
  pdb:
    enabled: false

extensions: {}
extraObjects: []
