apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-agent-prometheus-cred
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: grafana-agent-prometheus-cred
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app: grafana-agent
          argocd.argoproj.io/instance: grafana-flow-agent
        annotations:
          secret.source: external
      data:
        host: https://prometheus-prod-01-eu-west-0.grafana.net
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        key: grafana-cloud-prometheus-user
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        key: grafana-cloud-default-token
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
        metadataPolicy: None
