# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/k8s-monitoring-helm/refs/heads/main/charts/k8s-monitoring/values.schema.json
# Examples https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/docs/examples/features/cluster-events/default/values.yaml
cluster:
  name: hetzner-k8s
global:
  scrapeInterval: 30s

destinations:
  - name: grafana-com-metrics
    type: prometheus
    url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: grafana-agent-prometheus-cred
      namespace: monitoring
  - name: grafana-com-loki
    type: loki
    url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: grafana-agent-loki-cred
      namespace: monitoring
  - name: grafana-com-tempo
    type: otlp
    protocol: grpc
    url: https://tempo-eu-west-0.grafana.net:443
    metrics: { enabled: false }
    logs: { enabled: false }
    traces: { enabled: true }
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: grafana-agent-tempo-cred
      namespace: monitoring
  - name: grafana-cloud-otlp-endpoint
    type: otlp
    url: https://otlp-gateway-prod-eu-west-0.grafana.net./otlp
    protocol: http
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: grafana-agent-otl-cred
      namespace: monitoring
    metrics:
      enabled: true
    logs:
      enabled: true
    traces:
      enabled: true
clusterMetrics:
  enabled: true
  # https://github.com/sustainable-computing-io/kepler
  kepler:
    enabled: false
  # https://github.com/opencost/opencost
  opencost:
    enabled: true
    metricsSource: grafana-com-metrics
    opencost:
      exporter:
        defaultClusterId: hetzner-k8s
      prometheus:
        existingSecretName: grafana-agent-prometheus-cred
        external:
          url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom
  windows-exporter:
    deploy: false
  node-exporter:
    deploy: true
    podAnnotations:
      k8s.grafana.com/logs.job: integrations/node_exporter
      cluster-autoscaler.kubernetes.io/enable-ds-eviction: "true"
clusterEvents:
  enabled: true
nodeLogs:
  enabled: false
podLogs:
  enabled: true
alloy-metrics:
  enabled: true
alloy-logs:
  enabled: true
alloy-singleton:
  enabled: true
alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
      - name: jaeger-grpc
        port: 14250
        targetPort: 14250
        protocol: TCP
prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true
  podMonitors:
    enabled: true
  serviceMonitors:
    enabled: true
applicationObservability:
  enabled: true
  connectors:
    grafanaCloudMetrics:
      enabled: true
  receivers:
    jaeger:
      grpc:
        enabled: true
        port: 14250
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
extraObjects: []
