apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: harbor-admin-creds
    creationPolicy: Owner

  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: example-cookie-secret
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
