apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
  - chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.*
    helm:
      releaseName: cert-manager
      valuesObject:
        installCRDs: true
  - repoURL: https://github.com/hegerdes/GitOps.git
    targetRevision: HEAD
    path: infra/hcloud-test/cluster-critical/cert-manager
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  info:
    - name: 'Chart Info'
      value: 'https://artifacthub.io/packages/helm/cert-manager/cert-manager'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
