apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
  - chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.*
    helm:
      releaseName: external-dns-azure
      valuesObject:
        provider: azure
        extraVolumes:
          - name: secrets
            secret:
              secretName: external-dns-azure
              items:
                - key: azure.json
                  path: azure.json
        extraVolumeMounts:
          - name: secrets
            mountPath: /etc/kubernetes/azure.json
            subPath: azure.json
  - chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.*
    helm:
      releaseName: external-dns-aws
      valuesObject:
        provider:
          name: aws
        extraVolumes:
          - name: secrets
            secret:
              secretName: external-dns-aws
              items:
                - key: credentials
                  path: credentials
        extraVolumeMounts:
          - name: secrets
            mountPath: /etc/kubernetes/.aws
        env:
          - name: AWS_CONFIG_FILE
            value: /etc/kubernetes/.aws/credentials
  - repoURL: https://github.com/hegerdes/GitOps.git
    targetRevision: HEAD
    path: infra/hcloud-test/cluster-critical/external-dns
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
  info:
    - name: 'Chart Info'
      value: 'https://artifacthub.io/packages/helm/external-dns/external-dns'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
