apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
  - chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.*
    helm:
      releaseName: external-dns
      valuesObject:
        provider: azure
        extraVolumes:
          - name: secrets
            secret:
              secretName: external-dns
              items:
                - key: azure.json
                  path: azure.json
        extraVolumeMounts:
          - name: secrets
            mountPath: /etc/kubernetes/azure.json
            subPath: azure.json
  - repoURL: https://github.com/hegerdes/GitOps.git
    targetRevision: HEAD
    path: infra/hcloud-test/cluster-critical/external-dns
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
  info:
    - name: 'Chart Info Hetzner-Cloud-Controller'
      value: 'https://github.com/hetznercloud/hcloud-cloud-controller-manager'
    - name: 'Chart Info Hetzner-CSI-Driver'
      value: 'https://github.com/hetznercloud/csi-driver'
    - name: 'Chart Info Hetzner-LB-Exporter'
      value: 'https://github.com/wacken89/hetzner-load-balancer-prometheus-exporter'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
