apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-controller
  namespace: argocd
spec:
  project: default
  sources:
  - chart: policy-controller
    repoURL: https://sigstore.github.io/helm-charts
    targetRevision: 0.*
    helm:
      releaseName: policy-controller
      valuesObject:
        webhook:
          namespaceSelector:
            matchExpressions:
              - key: policy.sigstore.dev/include
                operator: In
                values: ["true"]
  - repoURL: https://github.com/hegerdes/GitOps.git
    targetRevision: HEAD
    path: infra/hcloud-test/cluster-critical/policy-controller
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cosign-system
  info:
    - name: 'Chart Info'
      value: 'https://artifacthub.io/packages/helm/sigstore/policy-controller'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences: []
  # - kind: MutatingWebhookConfiguration
  #   group: "*"
  #   jqPathExpressions:
  #   - .webhooks[].namespaceSelector.matchExpressions
  # - kind: ValidatingWebhookConfiguration
  #   group: "*"
  #   jqPathExpressions:
  #   - .webhooks[].namespaceSelector.matchExpressions
  # - group: "*"
  #   kind: "*"
  #   managedFieldsManagers:
  #   - kube-controller-manager
