apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconf-template
  namespace: kube-system
data:
  kubeconfig: |
    kind: Config
    apiVersion: v1
    current-context: default
    contexts:
      - name: default
        context:
          cluster: kubernetes
          user: app
    clusters:
      - name: kubernetes
        cluster:
          server: "https://kubernetes.default:443"
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
      - name: app
        user:
          tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
