apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wasm-demo
  namespace: argocd
  labels:
    name: wasm-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hegerdes/GitOps.git
    targetRevision: HEAD
    path: k8s-deploy/hcloud-test/manifest-wasm-demo
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: wasm
  info:
    - name: 'Example:'
      value: 'https://example.com'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
