ci_access:
  projects:
    - id: hegerdes/gitops
    - id: hegerdes/gitlab-actions
    - id: hegerdes/reddvid-combined
    - id: hegerdes/demo-app-flask-nuxt

  groups:
    - id: hegerdes

user_access:
  access_as:
    user: {}
  projects:
    - id: hegerdes/gitops
  groups:
    - id: hegerdes
