ci_access:
  projects:
    - id: hegerdes/gitops
  groups:
    - id: hegerdes
      default_namespace: default
    - id: reddvid
      default_namespace: reddvid

user_access:
  access_as:
    user: {}
  projects:
    - id: hegerdes/gitops
  groups:
    - id: hegerdes
