apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox-secrets-store-inline
  labels:
    app: busybox-secret-csi
spec:
  selector:
    matchLabels:
      app: busybox-secret-csi
  template:
    metadata:
      labels:
        app: busybox-secret-csi
    spec:
      containers:
        - name: busybox
          resources: {}
          image: busybox
          command:
            - sleep
            - 7d
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-hegerdes-example
            nodePublishSecretRef: # Only required when using service principal mode
              name: secrets-store-creds # Only required when using service principal mode
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-hegerdes-example
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: hegerdes
    tenantID: 295b5ac3-2e4e-4ade-85d8-7dc31617bc2c
    objects: |
      array:
        - |
          objectName: grafana-cloud-loki-user
          objectType: secret
