apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret-sso
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store # name of the SecretStore (or kind specified)
  target:
    name: argocd-secret-sso # name of the k8s Secret to be created
    creationPolicy: Owner
  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: dex.acme.clientSecret
      remoteRef:
        key: github-oauth-argocd-secret
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
    - secretKey: webhook.github.secret
      remoteRef:
        key: github-webhook-secret
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
