apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ca-hegerdes-local
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: ca-hegerdes-local
    creationPolicy: Owner

  data:
    - secretKey: tls.crt
      remoteRef:
        key: tls-hegerdes-local-crt
        decodingStrategy: Auto # can be None, Base64, Base64URL or Auto
    - secretKey: tls.key
      remoteRef:
        key: tls-hegerdes-local-key
        decodingStrategy: Auto # can be None, Base64, Base64URL or Auto
