apiVersion: v1
kind: Namespace
metadata:
  name: wasm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crun-wasm
  namespace: wasm
  labels:
    app: crun-wasm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crun-wasm
  template:
    metadata:
      name: hello-wasm
      annotations:
        # Needed for crun wasm
        module.wasm.image/variant: compat-smart
      labels:
        app: crun-wasm
    spec:
      runtimeClassName: crun
      containers:
        - name: hello-wasm
          image: docker.io/wasmedge/example-wasi-http:latest
          #image: wasmedge/example-wasi:latest
          #image: michaelirwin244/wasm-example
          resources: {}
          env:
            - name: foo
              value: bar
# apiVersion: v1
# kind: Pod
# metadata:
#   name: hello-wasm
#   annotations:
#     module.wasm.image/variant: compat-smart
# spec:
#   hostNetwork: true
#   containers:
#   - name: hello-wasm
#     image: docker.io/wasmedge/example-wasi-http:latest
#     #image: wasmedge/example-wasi:latest
#     #image: michaelirwin244/wasm-example
