# Test Grafana Values
replicas: 3

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
  path: /

  # pathType is only for k8s >= 1.1=
  pathType: Prefix

  hosts:
    - grafana.k8s.henrikgerdes.me
  tls:
    - secretName: ing-ssl-grafana
      hosts:
       - grafana.k8s.henrikgerdes.me


# Administrator credentials when not using an existing secret (see below)
adminUser: admin
adminPassword: MySuperSecurePassword4U

# Use an existing secret for the admin user.
admin:
  ## Name of the secret. Can be templated.
  existingSecret: ""
  userKey: admin-user
  passwordKey: admin-password
