apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeseal-key
  namespace: sealed-secrets
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: kubeseal-key
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      metadata:
        labels:
            sealedsecrets.bitnami.com/sealed-secrets-key: active
  data:
      # Decoding strategy can be None, Base64, Base64URL or Auto
    - secretKey: tls.crt
      remoteRef:
        key: k8s-kubeseal-demo-cert
        decodingStrategy: None
    - secretKey: tls.key
      remoteRef:
        key: k8s-kubeseal-demo-key
        decodingStrategy: None

