apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hcloud-token
  namespace: kube-system
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store               # name of the SecretStore (or kind specified)
  target:
    name: hcloud  # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app: grafana-agent
          argocd.argoproj.io/instance: grafana-flow-agent
        annotations:
          secret.source: external
      data:
        network: https://prometheus-prod-01-eu-west-0.grafana.net
        token: '{{ .token }}'
  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: token
      remoteRef:
        key: hcloud-k8s-token
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
