apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: policy-controller-cosign-key
  namespace: cosign-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: policy-controller-cosign-key
    creationPolicy: Owner

  data:
    - secretKey: cosign.pub
      remoteRef:
        key: cosign-artifact-sign-pub
        decodingStrategy: Auto # can be None, Base64, Base64URL or Auto
