apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    name: grafana
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hegerdes/GitOps.git
    targetRevision: HEAD
    path: infra/hcloud-test/helm-grafana
    helm:
      releaseName: grafana
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  info:
    - name: 'Chart Info'
      value: 'https://example.com'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
