apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  project: default
  sources:
  - chart: oauth2-proxy
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: 6.*
    helm:
      releaseName: oauth2-proxy
      valuesObject:
        config:
          existingSecret: oauth2-client-conf
          configFile: |
            provider = "github"
            email_domains = [ "*" ]
            upstreams = [ "file:///dev/null" ]
            scope = "user"
            show_debug_on_error = "true"
            skip_provider_button = "true"
            pass_access_token = "true"
            pass_authorization_header = "true"
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
          path: /oauth2
          pathType: Prefix
          hosts:
          - demo.k8s.henrikgerdes.me
          tls:
          - hosts:
            - demo.k8s.henrikgerdes.me
            secretName: oauth2-proxy-cert-ing
  - repoURL: https://github.com/hegerdes/GitOps.git
    targetRevision: HEAD
    path: infra/hcloud-test/oauth2-proxy
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  info:
    - name: 'Chart Info'
      value: 'https://artifacthub.io/packages/helm/oauth2-proxy/oauth2-proxy'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
