---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    token: AgBjDMBzNcn18taX1lULhmQDLnZGHJon6Au0P1KXR9PI7A7bMXM6Whda/VPp+Ykpnde9oUvVbaYycMsmrKRECf8P6Pcl/9efvfEwpXrWYexKyskgHN4YzS5KhXMEWDXGG8LhH7S285m0lrFvwT206NaRCD+xsr7atoqzYAf2b5+/doeFD0SsyWHXivqBRhguOUPv9fwjnLEPdKrrjzt5NFQ7TKBmxDkDa1jjPb3U9QbR7rEw86f4ei3qMFV+Pa09e90Bssn8yizEk2SOPCyBgrrSdY9rixM9Ox+axQNUu+sa8HKG1FZqn0669K48DvoKWhlkQ3jgF3pIjXRO5q5lP+nIHt12E5Wh67MAnudjPHJgkjoTvRMD/pSyz94lycwzx8SPFQ0V49h3iLGBbEdyHlXmfT5u6zj5idlezPcQenl8QZmoB+91ba1D06ZTs4qzQnr+x6e9NktX/NFoAjZwS92y+iUyWKAZ7wTrTjzLhkW8Vy51YU0lOE8INkIPMOJ92283GyBLeJFxdsGMc+LK7wFH0aauJ4Dt9psQkz8RIUVN4XGHplFxlPePlo6lnieYJK0rMj4hjGE/m7zsR8+VPdYb3JTGDcXjx5F404VptUtcn+MJpmc9FcYeFyIBk6GdJDOwQMRsw5vUuOS7sQqNJl+TOo3/t5wguvOa+iUxO337oOMUGdSf3GsLosrZIzRbu6z1NqiWwkI=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
