apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret-sso
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: argocd-secret-sso
    creationPolicy: Owner

  data:
    - secretKey: dex.acme.clientId
      remoteRef:
        key: github-oauth-argocd-client-id
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
    - secretKey: dex.acme.clientSecret
      remoteRef:
        key: github-oauth-argocd-secret
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
    - secretKey: webhook.github.secret
      remoteRef:
        key: github-webhook-secret
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
