apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-conf
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            hks.hegerdes.com/managed-cluster: "true"
            hks.hegerdes.com/cluster-type: "downstream"
  template:
    metadata:
      name: "{{.name}}-cluster-conf"
    spec:
      project: default
      source:
        repoURL: https://github.com/hegerdes/GitOps.git
        targetRevision: feat/hks
        path: k8s-apps/hegerdes-kubernetes-service/clustes-shared
      destination:
        server: "{{.server}}"
        namespace: kube-system
      info:
        - name: "Source Info"
          value: "https://github.com/hegerdes/GitOps"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 3
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 5m
