apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-conf
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            hks.hegerdes.com/managed-cluster: "true"
            hks.hegerdes.com/cluster-type: "downstream"
            # argocd.argoproj.io/kubernetes-version: "1.35"
  template:
    metadata:
      name: "{{.name}}-cluster-conf"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/hegerdes/GitOps.git
          targetRevision: feat/hks
          path: k8s-apps/hegerdes-kubernetes-service/shared/helm-rendering
          helm:
            valuesObject:
              extraObjects:
                - apiVersion: v1
                  kind: ConfigMap
                  metadata:
                    name: kubeadm-config
                    namespace: kube-system
                  data:
                    ClusterConfiguration: |
                      apiVersion: kubeadm.k8s.io/v1beta4
                      kind: ClusterConfiguration
                      caCertificateValidityPeriod: 87600h0m0s
                      certificateValidityPeriod: 8760h0m0s
                      certificatesDir: /etc/kubernetes/pki
                      clusterName: {{.name}}
                      controlPlaneEndpoint: {{ index .metadata.annotations "hks.hegerdes.com/public-host" }}:6443
                      dns: {}
                      encryptionAlgorithm: RSA-2048
                      imageRepository: registry.k8s.io
                      kubernetesVersion: v{{ index .metadata.labels "argocd.argoproj.io/kubernetes-version" }}.0
                      networking:
                        dnsDomain: cluster.local
                        podSubnet: 10.244.0.0/16
                        serviceSubnet: 10.96.0.0/16
        - repoURL: https://github.com/hegerdes/GitOps.git
          targetRevision: feat/hks
          path: k8s-apps/hegerdes-kubernetes-service/clustes-shared
      destination:
        server: "{{.server}}"
        namespace: kube-system
      info:
        - name: "Source Info"
          value: "https://github.com/hegerdes/GitOps"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 3
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 5m
