apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hks-gateway
  namespace: envoy-gateway
spec:
  allowedListeners:
    namespaces:
      from: Selector # can be Same, Selector, All, None
      selector:
        hks.hegerdes.com/managed-cluster: "true"
  gatewayClassName: envoy
  infrastructure:
    annotations:
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/name: k8s-hks-gateway-lb
      load-balancer.hetzner.cloud/network: k8s-network
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
      load-balancer.hetzner.cloud/ipv6-disabled: "true"
  listeners:
    - name: tls
      protocol: TLS
      port: 6443
      hostname: "*.hks.eu-central.hegerdes.com"
      allowedRoutes:
        namespaces:
          from: All
        kinds:
          - kind: TLSRoute
      tls:
        mode: Passthrough
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: enable-proxy-protocol-policy-hks
  namespace: envoy-gateway
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: hks-gateway
  proxyProtocol:
    optional: false
