apiVersion: v2
name: grafana
description: A Meta-Helm-Chart for k8s Grafana


type: application
version: 7.0.19
appVersion: "10.2.2"

dependencies:
- name: grafana
  version: 7.0.19
  repository: https://grafana.github.io/helm-charts
