name: Build-and-Publish-Helm-Chart

on:
  push:

permissions:
  contents: read
  packages: write
  id-token: write
  security-events: write

env:
  # ANSIBLE
  ANSIBLE_HOST_KEY_CHECKING: 'false'
  ANSIBLE_FORCE_COLOR: 'true'
  ANSIBLE_LOOKUP_PLUGINS: '{{ ANSIBLE_HOME ~ "/plugins/lookup:/usr/share/ansible/plugins/lookup":/app/playbooks/lookup_plugins ${{ github.workspace }}/playbooks/lookup_plugins }}'

jobs:
  build-and-publish-charts:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: hegerdes/AnsiblePlaybooks
          path: playbooks
          token: ${{ secrets.ORG_GITHUB_PAT }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: hegerdes/inventories
          path: inventories
          token: ${{ secrets.ORG_GITHUB_PAT }}

      - name: Install Ansible
        working-directory: playbooks
        run: pip install -r requirements.txt

      - name: Setting up vars
        run: |
          # Provison infra
          echo "Setting up secrets and agents"
          mkdir -p ~/.ssh
          chmod 700 -R ~/.ssh
          eval $(ssh-agent -s) > /dev/null
          az keyvault secret show --vault-name ${{ github.repository_owner }} --name ssh-rsa-${{ github.repository_owner }}-pub \
          | jq -r .value | base64 -d > ~/.ssh/id_rsa.pub
          az keyvault secret show --vault-name ${{ github.repository_owner }} --name ssh-25519-ci-pub \
          | jq -r .value | base64 -d > ~/.ssh/cloud-test.pub
          az keyvault secret show --vault-name ${{ github.repository_owner }} --name ssh-25519-ci-pvt \
          | jq -r .value | base64 -d | tr -d '\r' | ssh-add - > /dev/null
          HCLOUD_TOKEN=$(az keyvault secret show --vault-name ${{ github.repository_owner }} --name hcloud-k8s-token | jq -r .value)
          echo "::add-mask::$HCLOUD_TOKEN"
          echo "HCLOUD_TOKEN=$HCLOUD_TOKEN" >> "$GITHUB_ENV"

      - name: Terraform Run
        working-directory: inventories/hetzner-test/terraform
        continue-on-error: true
        run: |
          terraform init
          terraform plan -out plan.infra
          terraform apply -auto-approve plan.infra
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Run Docker image
        continue-on-error: true
        uses: docker://hegerdes/playbooks:latest
        with:
          entrypoint: ansible-playbook
          args: --version

      - name: Ansible Run
        continue-on-error: true
        run: |
          ansible-inventory -i inventories/hetzner-test/hcloud.yml --graph
          ansible-playbook -i inventories/hetzner-test/hcloud.yml playbooks/local.yml

      - name: Azure Logout
        continue-on-error: true
        run: |
            az logout
            az cache purge
            az account clear
